config/routes.rb
Rails.application.routes.draw do

  root 'rss_feeds#index'
  resources :rss_feeds do
    collection do
      get 'feed_entries'
    end
  end

end

app/models/rss_entry.rb
class RssEntry < ActiveRecord::Base
  belongs_to :rss_feed
end

app/models/rss_feed.rb
class RssFeed < ActiveRecord::Base
  validates_presence_of :name, :url

  has_many :rss_entries, dependent: :destroy

  after_save :load_rss_feeds!

  def load_rss_feeds!
  	Resque.enqueue(FetchRecentFeeds, self.id) if self.url_changed?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/rss_feeds_controller.rb
class RssFeedsController < ApplicationController
  before_action :set_rss_feed, only: [:edit, :show, :destroy, :update]

  def index
    @rss_feeds = RssFeed.all
  end

  def new
    @rss_feed = RssFeed.new
  end

  def create
    @rss_feed = RssFeed.new(rss_feed_params)
    
    if @rss_feed.save
      flash[:success] = 'Rss feed created successfully.'
      redirect_to rss_feeds_url
    else
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    if @rss_feed.update_attributes(rss_feed_params)
      flash[:success] = 'Rss feed updated successfully.'
      redirect_to rss_feed_url(@rss_feed)
    else
      render 'edit'
    end
  end

  def destroy
    @rss_feed.destroy
    flash[:success] = 'Rss Feed Deleted Successfully.'
    redirect_to rss_feeds_url
  end

  def feed_entries
    @feed_entries = RssEntry.order('published desc').paginate(:page => params[:page], :per_page => 10)
  end

  private
    
    def set_rss_feed
      @rss_feed = RssFeed.find(params[:id])
    end

    def rss_feed_params
      params.require(:rss_feed).permit(:name, :url)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/rss_feeds_helper.rb
module RssFeedsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RssfeedsReader</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link href='https://fonts.googleapis.com/css?family=Source+Sans+Pro:400,600,700' rel='stylesheet' type='text/css' async="async"/>
</head>
<body>
  <nav class="navbar navbar-default">
    <div class="container-fluid">
      <div class="navbar-header">
        <button aria-controls="navbar" aria-expanded="false" data-target="#navbar" data-toggle="collapse" class="navbar-toggle collapsed" type="button">
          <span class="sr-only"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to 'Rss Feed Reader', rss_feeds_path, class: "navbar-brand" %>
      </div>
    </div><!--/.container-fluid -->
  </nav>
  <!-- Start alert -->
  <% if flash[:success] %>
    <div class="alert alert-success"><%= flash[:success] %></div>
  <% end %>  
  <!-- End alert -->
  <div class="container">
    <%= yield %>
  </div>
</body>
</html>

app/views/rss_entries/_rss_entry.html.erb
<div class="panel panel-default">
  <div class="panel-body">
    <%= link_to rss_entry.title, rss_entry.url, target: '_blank', class: 'name' %> 
    <% if rss_entry.published %>
      - <i> published <%= time_ago_in_words(rss_entry.published) %> ago.</i>
    <% end %>
  </div>
</div>

app/views/rss_feeds/_form.html.erb
<div class="panel-body">
  <%= form_for(@rss_feed, {class: 'form-horizontal'}) do |f| %>
    <div class="form-group row">
      <label class="col-lg-2 control-label" for="inputEmail1">Name</label>
      <div class="col-lg-5">
        <%= f.text_field :name, class: 'form-control' %>
      </div>
    </div>
    <div class="form-group row">
      <label class="col-lg-2 control-label" for="inputPassword1">Url</label>
      <div class="col-lg-5">
        <%= f.text_field :url, class: 'form-control' %>
      </div>
    </div>
    <div class="form-group row">
      <div class="col-lg-offset-2 col-lg-10">
        <%= f.submit "#{@rss_feed.new_record? ? 'Create' : 'Save'}", class: 'btn-u btn-u-green' %>
      </div>
    </div>
  <% end %>
</div>

<%= javascript_include_tag 'feed_validation' %>

app/views/rss_feeds/edit.html.erb
<div class="panel panel-green margin-bottom-40">
  <div class="panel-heading">
    <h3 class="panel-title">Edit Rss Feed</h3>
  </div>
  <%= render 'form' %>
</div>

app/views/rss_feeds/feed_entries.html.erb
<div id="feed-container">
  <div class="row">
    <div class="col-md-offset-8 col-md-4">
      <input placeholder="Search" class="search form-control">
      <br><br>
    </div>
  </div>
  <div class="row">
    <div class='list col-md-12'>
      <%= render @feed_entries %>
    </div>
  </div>
</div>

<%= will_paginate @feed_entries %>

<script type="text/javascript">
  $(function() {
    if ($('.pagination').length) {
      $(window).scroll(function() {
        var url;
        url = $('.pagination .next_page').attr('href');
        if (url && $(window).scrollTop() > $(document).height() - $(window).height() - 50) {
          $('.pagination').text("Fetching more examples...");
          return $.getScript(url);
        }
      });
      return $(window).scroll();
    }
  });

  var options = {
    valueNames: [ 'name']
  };

  var feedList = new List('feed-container', options);
</script>

app/views/rss_feeds/feed_entries.js.erb
$('#feed-container').append('<%= j render(@feed_entries) %>');
<% if @feed_entries.next_page %>
  $('.pagination').replaceWith('<%= j will_paginate(@feed_entries) %>');
<% else %>
  $('.pagination').remove();
<% end %>

app/views/rss_feeds/index.html.erb
<div class="row">
  <div class='col-md-10'>
    <%= link_to 'Feeds Entries', feed_entries_rss_feeds_path, class: 'pull-right' %>    
  </div>
  <div class="col-md-2">
    <%= link_to 'Create Rss Feed', new_rss_feed_path, class: 'pull-right' %>   
  </div>
</div>
 

<table class="table">
  <thead>
    <tr>
      <th>#</th>
      <th>Name</th>
      <th>Url</th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @rss_feeds.each.with_index(1) do |feed, index| %>  
      <tr>
        <th scope="row"><%= index %></th>
        <td><%= feed.name.capitalize %></td>
        <td><%= feed.url %></td>
        <td>
          <%= link_to "<i class='fa fa-pencil' aria-hidden='true'></i>".html_safe, edit_rss_feed_path(feed) %>
        </td>  
        <td>
          <%= link_to "<i class='fa fa-times' aria-hidden='true'></i>".html_safe, rss_feed_path(feed), method: :delete, data: {confirm: "Are you sure?"} %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/rss_feeds/new.html.erb
<div class="panel panel-green margin-bottom-40">
  <div class="panel-heading">
    <h3 class="panel-title">New Rss Feed</h3>
  </div>
  <%= render 'form' %>
</div>

app/views/rss_feeds/show.html.erb
<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Url</th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><%= @rss_feed.name.capitalize %></td>
      <td><%= @rss_feed.url %></td>
      <td>
        <%= link_to "<i class='fa fa-pencil' aria-hidden='true'></i>".html_safe, edit_rss_feed_path(@rss_feed) %>
      </td>  
      <td>
        <%= link_to "<i class='fa fa-times' aria-hidden='true'></i>".html_safe, rss_feed_path(@rss_feed), method: :delete, data: {confirm: "Are you sure?"} %>
      </td>
    </tr>
  </tbody>
</table>